# Generated by Django 6.0.2 on 2026-02-27 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='💎', help_text='Emoji or icon class', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Raffle Categories',
            },
        ),
        migrations.AddField(
            model_name='raffle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffles', to='raffle.rafflecategory'),
        ),
    ]
