# Generated by Django 6.0.2 on 2026-02-27 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_raffleorganizerprofile_partner_id_and_more'),
        ('raffle', '0003_raffle_is_revoked_raffle_revocation_reason_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='partner_referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_raffles', to='accounts.raffleorganizerprofile'),
        ),
        migrations.CreateModel(
            name='RaffleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payout_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('host_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('system_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('partner_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='raffle.raffle')),
            ],
        ),
    ]
