# Generated by Django 6.0.2 on 2026-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0004_raffle_partner_referral_code_raffle_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rafflewallet',
            name='payout_pool_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
