# Generated by Django 6.0.2 on 2026-02-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0006_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
