# Generated by Django 6.0.2 on 2026-02-27 20:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0007_raffle_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleanalytics',
            name='unclaimed_prizes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
