# Generated by Django 6.0.2 on 2026-02-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0008_raffleanalytics_unclaimed_prizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffleanalytics',
            name='raffle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='raffle.raffle'),
        ),
    ]
