# Generated by Django 6.0.2 on 2026-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffleorganizerprofile',
            name='partner_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='raffleorganizerprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
